#!/usr/bin/env bash
# Wrapper to fix compilation on worker nodes on Theta
#
# The underlying problem is that the Cray library versions (and thus paths)
# are slightly different on worker nodes relative to the login node. Since
# we build openmpi on the login node, its compiler wrappers get the paths
# from the login node, and thus don't work on worker nodes.
#
# If Theta is fixed to have the same versions of libraries everywhere,
# then this wrapper should be removed.
#
# The reason we need to compile on worker nodes is because for CASPER apps,
# that use Firedrake DSL compiler we do not support cross-compilation yet.

$EPREFIX/usr/bin/$(basename $0) "$@" $(pkg-config --libs cray-ugni cray-xpmem cray-udreg)
