#!/bin/bash

set -e

self_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
EPREFIX=$(cd -- "$(dirname ${self_dir})"/ && pwd)
source "${self_dir}"/pscommon.sh

if [[ "$#" -lt 6 ]]
then
	echo "Usage: $0 cluster[:part] arch[:gpu] mem_per_cpu nodes tasks_per_node max_max_time [salloc_arg...]" 1>&2
	exit 1
fi

cluster_part=$1
arch_gpu=$2
mem_per_cpu=$3
nodes=$4
tasks_per_node=$5
max_time=$6

shift 6
if [[ "${cluster_part}" =~ : ]]
then
	cluster="$(echo ${cluster_part} | cut -d':' -f1)"
	part="$(echo ${cluster_part} | cut -d':' -f2)"
else
	cluster="${cluster_part}"
	part=""
fi

if [[ "${arch_gpu}" =~ : ]]
then
	arch="$(echo ${arch_gpu} | cut -d':' -f1)"
	gpu="$(echo ${arch_gpu} | cut -d':' -f2-)"
else
	arch="${arch_gpu}"
	gpu=""
fi

args=()
if [[ -n "${part}" ]]
then
	args+=(--partition "${part}")
fi
if [[ -n "${gpu}" ]]
then
	args+=(--gres=gpu:${gpu})
fi

if [[ "${mem_per_cpu}" = "all" ]]
then
	args+=(--mem 0)
else
	args+=(--mem-per-cpu "${mem_per_cpu}")
fi

# /var/spool/slurm/slurm.conf
# SallocDefaultCommand="exec env PATH=/usr/bin:/bin srun -n1 -N1
# 	--export=HOME,PATH,TERM,USER --mem-per-cpu=0 --gres=gpu:0 --cpu_bind=no
# 	--pty --preserve-env --mpi=pmi2 ${DISPLAY:+--x11=first} $SHELL -l"
runexec salloc --nodes "${nodes}" --ntasks-per-node "${tasks_per_node}" \
	--constraint "$(constraint "${cluster}" "${arch}")"  ${args[@]} \
	--time "${max_time}" "$@" \
	env PATH=/usr/bin:/bin srun -n1 -N1 \
	--export=HOME,PATH,TERM,USER ${args[@]} --cpu_bind=no \
	--pty --preserve-env \
	$SHELL "${EPREFIX}"/startprefix
