#!/bin/bash

set -e

self_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source "${self_dir}"/pscommon.sh

if [[ "$#" -lt 1 ]]
then
	echo "Usage: $0 prefix" 1>&2
	exit 1
fi

EPREFIX="$(cd -- "$1"/ && pwd)"
shift
if [[ "$#" -gt 0 ]]
then
	exec "${EPREFIX}"/startprefix -c "$*"
else
	exec "${EPREFIX}"/startprefix
fi
