#!/usr/bin/env bash

# Wraps mpirun with a wrapper that creates and cleans up temp dir (TMPDIR)

if ! type wtmp 1>/dev/null 2>/dev/null
then
	echo "wtmp command not found (.prefixrc was not sourced?)" 1>&2
	exit 1
fi

run() {
	echo "$@"
	"$@"
}

mpi_args=(
)

#UCX_TLS=ud,shm

# careful to not invoke via any other name than 'mpirun',
# since the underlying binary may be sensitive to argv[0]

which --all mpirun | while read line
do
	if [[ $(realpath "${line}") != "$(realpath "${BASH_SOURCE[0]}")" ]]
	then
		CLUSTER=usc-discovery SPACE_MB=16 \
			run wtmp env "${line}" ${mpi_args[@]} "$@"
	fi
done
